version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      - MYSQL_DATABASE=ecuadorian_Sign_Language_base
      - MYSQL_USER=ecuadorian_Sign_Language_user
      - MYSQL_PASSWORD=tesisroot
      - MYSQL_ROOT_PASSWORD=tesisroot
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "4200:80"
    expose:
      - "4200"
    environment:
      - DATABASE_URL=mysql://ecuadorian_Sign_Language_user:tesisroot@db:3306/ecuadorian_Sign_Language_base
    depends_on:
      - db
    links:  # Agregar esta sección para establecer enlaces
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    links:
      - db
    command: ["apache2-foreground"]
    extra_hosts:
      - "localhost:127.0.0.1"

volumes:
  db_data:
