# Usar una imagen base ligera de Python
FROM python:3.10-slim-buster

# Establecer un directorio de trabajo
WORKDIR /app

# Suprimir diálogos de interacción durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    curl \
    wget \
    software-properties-common \
    gnupg2 \
    libffi-dev \
    gcc \
    default-libmysqlclient-dev \
    libmariadb-dev-compat \
    libmariadb-dev \
    pkg-config \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar el archivo de requerimientos y el código fuente al contenedor
COPY requirements.txt .
COPY . /app/

# Instalar las dependencias de Python
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expone el puerto MySQL (3306) para que se pueda acceder desde fuera del contenedor
EXPOSE 4200

# Iniciar la aplicación
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
