
CREATE TABLE palabra (
                id_palabra INT AUTO_INCREMENT NOT NULL,
                palabra VARCHAR(100) NOT NULL,
                descripcion VARCHAR(200) NOT NULL,
                video VARCHAR(200) NOT NULL,
                PRIMARY KEY (id_palabra)
);


CREATE TABLE caracter (
                id_caracter INT AUTO_INCREMENT NOT NULL,
                caracter VARCHAR(2) NOT NULL,
                video VARCHAR(200) NOT NULL,
                PRIMARY KEY (id_caracter)
);

CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE palabra AUTO_INCREMENT = 1;
ALTER TABLE caracter AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;

INSERT INTO caracter (caracter, video) VALUES ('0', '0.webm');
INSERT INTO caracter (caracter, video) VALUES ('1', '1.webm');
INSERT INTO caracter (caracter, video) VALUES ('2', '2.webm');
INSERT INTO caracter (caracter, video) VALUES ('3', '3.webm');
INSERT INTO caracter (caracter, video) VALUES ('4', '4.webm');
INSERT INTO caracter (caracter, video) VALUES ('5', '5.webm');
INSERT INTO caracter (caracter, video) VALUES ('6', '6.webm');
INSERT INTO caracter (caracter, video) VALUES ('7', '7.webm');
INSERT INTO caracter (caracter, video) VALUES ('8', '8.webm');
INSERT INTO caracter (caracter, video) VALUES ('9', '9.webm');
INSERT INTO caracter (caracter, video) VALUES ('a', 'a.webm');
INSERT INTO caracter (caracter, video) VALUES ('á', 'a.webm');
INSERT INTO caracter (caracter, video) VALUES ('b', 'b.webm');
INSERT INTO caracter (caracter, video) VALUES ('c', 'c.webm');
INSERT INTO caracter (caracter, video) VALUES ('d', 'd.webm');
INSERT INTO caracter (caracter, video) VALUES ('e', 'e.webm');
INSERT INTO caracter (caracter, video) VALUES ('é', 'e.webm');
INSERT INTO caracter (caracter, video) VALUES ('f', 'f.webm');
INSERT INTO caracter (caracter, video) VALUES ('g', 'g.webm');
INSERT INTO caracter (caracter, video) VALUES ('h', 'h.webm');
INSERT INTO caracter (caracter, video) VALUES ('i', 'i.webm');
INSERT INTO caracter (caracter, video) VALUES ('í', 'i.webm');
INSERT INTO caracter (caracter, video) VALUES ('j', 'j.webm');
INSERT INTO caracter (caracter, video) VALUES ('k', 'k.webm');
INSERT INTO caracter (caracter, video) VALUES ('l', 'l.webm');
INSERT INTO caracter (caracter, video) VALUES ('m', 'm.webm');
INSERT INTO caracter (caracter, video) VALUES ('n', 'n.webm');
INSERT INTO caracter (caracter, video) VALUES ('ñ', 'n.webm');
INSERT INTO caracter (caracter, video) VALUES ('o', 'o.webm');
INSERT INTO caracter (caracter, video) VALUES ('ó', 'o.webm');
INSERT INTO caracter (caracter, video) VALUES ('p', 'p.webm');
INSERT INTO caracter (caracter, video) VALUES ('q', 'q.webm');
INSERT INTO caracter (caracter, video) VALUES ('r', 'r.webm');
INSERT INTO caracter (caracter, video) VALUES ('s', 's.webm');
INSERT INTO caracter (caracter, video) VALUES ('t', 't.webm');
INSERT INTO caracter (caracter, video) VALUES ('u', 'u.webm');
INSERT INTO caracter (caracter, video) VALUES ('ú', 'u.webm');
INSERT INTO caracter (caracter, video) VALUES ('v', 'v.webm');
INSERT INTO caracter (caracter, video) VALUES ('w', 'w.webm');
INSERT INTO caracter (caracter, video) VALUES ('x', 'x.webm');
INSERT INTO caracter (caracter, video) VALUES ('y', 'y.webm');
INSERT INTO caracter (caracter, video) VALUES ('z', 'z.webm');

INSERT INTO palabra (palabra,descripcion, video) VALUES ('aceptar','aceptar','ACEPTAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('acusar','acusar','ACUSAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('agalla','agalla','AGALLA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('aguila','aguila','AGUILA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('albañil','albañil','ALBAÑIL.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('amadecasa','amadecasa','AMADECASA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('amasar','amasar','AMASAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('anfibio','anfibio','ANFIBIO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('ansiosa','ansiosa','ANSIOSA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('ansioso','ansioso','ANSIOSO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('armadillo','armadillo','ARMADILLO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('asi','asi','ASI.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('atraves','atraves','ATRAVES.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('atropellar','atropellar','ATROPELLAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('automático','automático','AUTOMÁTICO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('axila','axila','AXILA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bachillerato','bachillerato','BACHILLERATO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('barbon','barbon','BARBON.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('barrer','barrer','BARRER.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bebé','bebé','BEBÉ.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('billetera','billetera','BILLETERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bisexual','bisexual','BISEXUAL.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('blanca','blanca','BLANCA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('blanco','blanco','BLANCO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bobo','bobo','BOBO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bocacerrada','bocacerrada','BOCACERRADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('boda','boda','BODA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bolsadevalores','bolsadevalores','BOLSADEVALORES.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bolsillo','bolsillo','BOLSILLO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bondad','bondad','BONDAD.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bondadoso','bondadoso','BONDADOSO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bostezo','bostezo','BOSTEZO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('buena','buena','BUENA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('bueno','bueno','BUENO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('buenprovecho','buenprovecho','BUENPROVECHO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cachetada','cachetada','CACHETADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('caducada','caducada','CADUCADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('caducado','caducado','CADUCADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('calculadora','calculadora','CALCULADORA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('carajo','carajo','CARAJO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('carrera','carrera','CARRERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('carretera','carretera','CARRETERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('carton','carton','CARTON.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('casa','casa','CASA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('caspa','caspa','CASPA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('causa','causa','CAUSA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cementerio','cementerio','CEMENTERIO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('centro','centro','CENTRO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cepillo','cepillo','CEPILLO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('chef','chef','CHEF.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('chequera','chequera','CHEQUERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('chismosa','chismosa','CHISMOSA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('chismoso','chismoso','CHISMOSO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('chocolate','chocolate','CHOCOLATE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cilantro','cilantro','CILANTRO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('colchon','colchon','COLCHON.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('comadre','comadre','COMADRE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('comoestá','comoestá','COMOESTÁ.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('comparar','comparar','COMPARAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('compartir','compartir','COMPARTIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('comportamiento','comportamiento','COMPORTAMIENTO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('compromiso','compromiso','COMPROMISO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('comunidad','comunidad','COMUNIDAD.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('conmuchogusto','conmuchogusto','CONMUCHOGUSTO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('consulado','consulado','CONSULADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('contenta','contenta','CONTENTA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('contento','contento','CONTENTO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('contra','contra','CONTRA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('contraparte','contraparte','CONTRAPARTE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cooperar','cooperar','COOPERAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('copiar','copiar','COPIAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('corazon','corazon','CORAZON.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cordillera','cordillera','CORDILLERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('corrección','corrección','CORRECCIÓN.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('corrector','corrector','CORRECTOR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('corregir','corregir','CORREGIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cosa','cosa','COSA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('coser','coser','COSER.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('costurera','costurera','COSTURERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('costurero','costurero','COSTURERO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cruzarlaspiernas','cruzarlaspiernas','CRUZARLASPIERNAS.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cuerpo','cuerpo','CUERPO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('culantro','culantro','CULANTRO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('culpa','culpa','CULPA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('culpable','culpable','CULPABLE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cumplida','cumplida','CUMPLIDA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cumplido','cumplido','CUMPLIDO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('cumplir','cumplir','CUMPLIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('debajo','debajo','DEBAJO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('dedicacion','dedicacion','DEDICACION.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('defrente','defrente','DEFRENTE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('dejar','dejar','DEJAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('delgada','delgada','DELGADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('delgado','delgado','DELGADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('delito','delito','DELITO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('despacio','despacio','DESPACIO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('despedir','despedir','DESPEDIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('desvio','desvio','DESVIO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('diapositiva','diapositiva','DIAPOSITIVA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('disculpa','disculpa','DISCULPA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('disfrutar','disfrutar','DISFRUTAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('dividirseelgasto','dividirseelgasto','DIVIDIRSEELGASTO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('division','division','DIVISION.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('doblar','doblar','DOBLAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('docente','docente','DOCENTE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('ecuavoley','ecuavoley','ECUAVOLEY.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('embrague','embrague','EMBRAGUE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('emocion','emocion','EMOCION.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('empleadadomestica','empleadadomestica','EMPLEADADOMESTICA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('empujar','empujar','EMPUJAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('encaminarse','encaminarse','ENCAMINARSE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('encebollado','encebollado','ENCEBOLLADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('encima','encima','ENCIMA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('enfermo','enfermo','ENFERMO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('enfocar','enfocar','ENFOCAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('enfocarse','enfocarse','ENFOCARSE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('enfoque','enfoque','ENFOQUE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('enfrentar','enfrentar','ENFRENTAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('enfrente','enfrente','ENFRENTE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('ensalada','ensalada','ENSALADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('entrar','entrar','ENTRAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('entregar','entregar','ENTREGAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('entusiasmarse','entusiasmarse','ENTUSIASMARSE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('epoca','epoca','EPOCA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('escalera','escalera','ESCALERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('escolar','escolar','ESCOLAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('espalda','espalda','ESPALDA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('especialidad','especialidad','ESPECIALIDAD.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('especialista','especialista','ESPECIALISTA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('especializarce','especializarce','ESPECIALIZARCE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('espejo','espejo','ESPEJO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estafa','estafa','ESTAFA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estafador','estafador','ESTAFADOR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estafadora','estafadora','ESTAFADORA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estafar','estafar','ESTAFAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estarhastalacoronilla','estarhastalacoronilla','ESTARHASTALACORONILLA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estrecho','estrecho','ESTRECHO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('estupefacta','estupefacta','ESTUPEFACTA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('etapa','etapa','ETAPA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('eterna','eterna','ETERNA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('eterno','eterno','ETERNO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('excepcionalmente','excepcionalmente','EXCEPCIONALMENTE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('exprimidor','exprimidor','EXPRIMIDOR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fábrica','fábrica','FÁBRICA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fabricar','fabricar','FABRICAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('facil','facil','FACIL.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('factura','factura','FACTURA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('falda','falda','FALDA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fanesca','fanesca','FANESCA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('feliz','feliz','FELIZ.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fin','fin','FIN.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('florero','florero','FLORERO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('foca','foca','FOCA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fotocopiar','fotocopiar','FOTOCOPIAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fracasar','fracasar','FRACASAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fracaso','fracaso','FRACASO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('freir','freir','FREIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('frente','frente','FRENTE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fritura','fritura','FRITURA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('frontal','frontal','FRONTAL.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fuera','fuera','FUERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fumador','fumador','FUMADOR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fumadora','fumadora','FUMADORA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('fusible','fusible','FUSIBLE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('futuro','futuro','FUTURO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('gastronomia','gastronomia','GASTRONOMIA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('gatear','gatear','GATEAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('generosa','generosa','GENEROSA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('generoso','generoso','GENEROSO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('golpe','golpe','GOLPE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('golpear','golpear','GOLPEAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('gracias','gracias','GRACIAS.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('grasa','grasa','GRASA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('gratis','gratis','GRATIS.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('gritodeguerra','gritodeguerra','GRITODEGUERRA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('grosero','grosero','GROSERO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('guardarselainformación','guardarselainformación','GUARDARSELAINFORMACIÓN.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('guarderia','guarderia','GUARDERIA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('guata','guata','GUATA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('guitarra','guitarra','GUITARRA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('heladodemáquina','heladodemáquina','HELADODEMÁQUINA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('hipoacúsico','hipoacúsico','HIPOACÚSICO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('humildad','humildad','HUMILDAD.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('humilde','humilde','HUMILDE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('imitar','imitar','IMITAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('íntima','íntima','ÍNTIMA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('íntimo','íntimo','ÍNTIMO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('lactar','lactar','LACTAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('ladrillo','ladrillo','LADRILLO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('lagartija','lagartija','LAGARTIJA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('lanzada','lanzada','LANZADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('lanzado','lanzado','LANZADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('lavadora','lavadora','LAVADORA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('levantar','levantar','LEVANTAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('levantarse','levantarse','LEVANTARSE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('libro','libro','LIBRO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('llamar','llamar','LLAMAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('llamarse','llamarse','LLAMARSE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('llanura','llanura','LLANURA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('llevar1','llevar1','LLEVAR1.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('loba','loba','LOBA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('mamífero','mamífero','MAMÍFERO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('menopausia','menopausia','MENOPAUSIA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('mula','mula','MULA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('nunca','nunca','NUNCA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('oregano','oregano','OREGANO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('palma','palma','PALMA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('panela','panela','PANELA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pantufla','pantufla','PANTUFLA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pañal','pañal','PAÑAL.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pañuelo','pañuelo','PAÑUELO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('papa','papa','PAPA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('parar','parar','PARAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('peces','peces','PECES.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pedir','pedir','PEDIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pegar','pegar','PEGAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pelear','pelear','PELEAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pena','pena','PENA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pendeja','pendeja','PENDEJA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('perforadora','perforadora','PERFORADORA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('periodista','periodista','PERIODISTA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pesame','pesame','PESAME.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pesas','pesas','PESAS.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('pescado','pescado','PESCADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('piñata','piñata','PIÑATA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('piston','piston','PISTON.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('propuesta','propuesta','PROPUESTA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('psicologia','psicologia','PSICOLOGIA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('quedice','quedice','QUEDICE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('quemecuentas','quemecuentas','QUEMECUENTAS.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('quieto','quieto','QUIETO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('quiza','quiza','QUIZA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('remolque','remolque','REMOLQUE.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('respirar','respirar','RESPIRAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('sala','sala','SALA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('salami','salami','SALAMI.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('saldeaqui','saldeaqui','SALDEAQUI.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('saludar','saludar','SALUDAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('saludo','saludo','SALUDO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('seguridadaeroportuaria','seguridadaeroportuaria','SEGURIDADAEROPORTUARIA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('servicio','servicio','SERVICIO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('servilleta','servilleta','SERVILLETA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('servir','servir','SERVIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('siesta','siesta','SIESTA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('sindinero','sindinero','Sindinero.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('sobrina','sobrina','SOBRINA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('sobrino','sobrino','SOBRINO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('su','su','SU.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('subir','subir','SUBIR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('suyo','suyo','SUYO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('tacaña','tacaña','TACAÑA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('tacaño','tacaño','TACAÑO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('talvez','talvez','TALVEZ.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('tapar','tapar','TAPAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('taxi','taxi','TAXI.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('television','television','TELEVISION.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('temeraria','temeraria','TEMERARIA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('temporal','temporal','TEMPORAL.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('terminar','terminar','TERMINAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('tienda','tienda','TIENDA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('tocino','tocino','TOCINO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('todo','todo','TODO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('todoeldía','todoeldía','TODOELDÍA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('tomar','tomar','TOMAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('torear','torear','TOREAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('torera','torera','TORERA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('torero','torero','TORERO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('torturar','torturar','TORTURAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('universidad','universidad','UNIVERSIDAD.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('usada','usada','USADA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('usado','usado','USADO.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('usar','usar','USAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('utilizar','utilizar','UTILIZAR.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('vivienda','vivienda','VIVIENDA.webm');
INSERT INTO palabra (palabra,descripcion, video) VALUES ('yanomas','yanomas','YANOMAS.webm');

INSERT INTO `users`( `name`, `email`, `password`) VALUES ('admin','jcajasp2@est.ups.edu.ec','tesis.root1');
INSERT INTO `users`( `name`, `email`, `password`) VALUES ('admin','userroot','userroot');


